<a href="https://colab.research.google.com/github/FelipeBomfim-prog/ConversorPyhton/blob/main/trabalho1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#TRABALHO 1 DE INTRODUÇÃO A CIÊNCIA DE DADOS

*Scraping*: https://www.doispontos.com.br/livros?O=OrderByReleaseDateDESC#

Nesta cédula importamos as bibliotecas que iremos utilizar para fazer o scraping da página

In [1]:
from bs4 import BeautifulSoup
import requests
from pandas import DataFrame
from time import time

In [2]:

dicionário = {
    'Livros': [],
    'Autores': [],
    'Preços': [],
    'Assinantes': []
    
}

# Define a URL que vamos analisar
url = 'https://www.doispontos.com.br/livros?O=OrderByReleaseDateDESC#'

start = time()
for i in range(1000):
    ax_url = url + str(i + 1)
      
    # Faz a requisição da página
    r = requests.get(ax_url)

    # Cria um objeto BeautifulSoup com o conteúdo HTML da página
    soup = BeautifulSoup(r.content, 'html.parser')
    linhas_html = soup.prettify().splitlines()

    for i in range(len(linhas_html)):
        if linhas_html[i] == "                 Autor":
          #Remove os epaços a esquerda e adiciona na coluna de Livro
          livro = linhas_html[i-7].lstrip()
          dicionário['Livros'].append(livro)
          #Remove os epaços a esquerda e adiciona na coluna de Autores
          nome = linhas_html[i + 3].lstrip()
          dicionário['Autores'].append(nome)
          #Remove os epaços a esquerda e adiciona na coluna de Preço
          preço = linhas_html[i + 11].split('R$')[1].lstrip()
          dicionário['Preços'].append(preço)
          #Remove os epaços a esquerda e adiciona na coluna de Assinantes
          assinantes = linhas_html[i + 30]
          #Como assinantes retorna uma tag html<a> e uma <div> isso significa 2 coisas 
          #se <a> existe é porque o livro possui promoção 
          #se for <div> não existe promoção então repetimos o preço
          try:
             promo = (assinantes.split('data-product-price="')[1].split('"')[0]).split('R$')[1].lstrip()
             dicionário['Assinantes'].append(promo)
          except Exception:
              dicionário['Assinantes'].append(preço)
 
        

df1 = DataFrame(dicionário) 
display(df1)
#df2 = df1.loc[df['Preços'] != df1['Assinantes']]
# display(df2.head(5))
termino = time() - start
print(f'Tempo de leitura e alocação : {round(termino, 2)} segundos')

,Livros,Autores,Preços,Assinantes
0,NÃO VIVA UMA MENTIRA,ROD DREHER,"69,90","62,90"
1,NÃO COMEÇOU COM VOCÊ,MARK WOLYNN,"62,90","69,90"
2,A ALEGRIA DO MOVIMENTO,KELLY MCGONIGAL,"69,90","84,90"
3,FOFURA - NÚMEROS NA FAZENDA,REALLY DECENT BOOKS LTD.,"84,90","62,90"
4,"VOU-ME EMBORA, DISSE O TEMPO",BETINA OBRECHT,"62,90","84,90"
...,...,...,...,...
19995,DRAGON BALL VOL. 8,AKIRA TORIYAMA,"34,90","59,90"
19996,PÓ DE PAREDE,CAROL BENSIMON,"59,90","99,00"
19997,GÊNERO QUEER,MAIA KOBABE,"99,00","54,90"
19998,CORE COM GUIDO,LAURA WALL,"54,90","54,90"
19999,HORA DE ACORDAR COM GUIDO,LAURA WALL,"54,90","54,90"

Tempo de leitura e alocação : 267.73 segundos